name: 'Dependency Install'
description: 'With dependency caching'

runs:
  using: 'composite'

  steps:
    - name: Get yarn cache directory path as "$GITHUB_OUTPUT"
      id: yarn-config
      shell: bash
      run: echo "CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Restore yarn cache
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-config.outputs.CACHE_FOLDER }}
        key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-cache-

    - name: Install dependencies
      shell: bash
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install
