const ACCESSTOKEN = 'x-access-token';
const REFRESHTOKEN = 'x-refresh-token';
const USER_NOT_EXISTED = 'USER_NOT_EXISTED';
const INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN';
const TOKEN_EXPIRED = 'TOKEN_EXPIRED';

export {
  ACCESSTOKEN,
  INVALID_REFRESH_TOKEN,
  REFRESHTOKEN,
  TOKEN_EXPIRED,
  USER_NOT_EXISTED,
};
