const ACCESSTOKEN = 'x-access-token';
const REFRESHTOKEN = 'x-refresh-token';
const USER_NOT_EXISTED = 'USER_NOT_EXISTED';
const INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN';

export { ACCESSTOKEN, INVALID_REFRESH_TOKEN, REFRESHTOKEN, USER_NOT_EXISTED };
