name: Chromatic
on:
  pull_request:
    branches: [dev]

jobs:
  chromatic-deployment:
    runs-on: ubuntu-22.04
    steps:
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
