name: dev CI

on:
  pull_request:
    branches: [dev]

defaults:
  run:
    working-directory: ./

jobs:
  Continuous-Integration:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: ./.github/actions/yarn-install

      - name: Format
        run: yarn format

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'style: auto code format'

      - name: Check Lint
        run: yarn lint

      - name: Run test code
        run: yarn test
