name: dev deploy to AWS Cloudfront

on:
  push:
    branches: [dev]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    environment: dev-deployment

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Generate Environment Variables
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: |
          echo "REACT_APP_API_URL=$REACT_APP_API_URL" >> .env

      - name: Dependency Install
        uses: ./.github/actions/yarn-install

      - name: Build
        run: |
          yarn msw:cleanup
          yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./${{ secrets.BUILD_DIRECTORY }} s3://${{ secrets.DEV_AWS_S3_BUCKET }} --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.DEV_AWS_DISTRIBUTION_ID}} --paths "/*"
